### ISSUE TITLE
KQL Playground

### ISSUE THREAD

**Issue by FR4385** [rod-trent/MustLearnKQL#22]
Apologies if this is the not the right place to post this.  There doesn't appear to be any data in the playground.

https://aka.ms/LADemo

**Comment by SQLtattoo** [comment]
> Apologies if this is the not the right place to post this.  There doesn't appear to be any data in the playground.
> 
> https://aka.ms/LADemo

I just run a query against SecurityEvent, from my mobile, and it has data.
It should be fine. Maybe something else is the problem 🙂

**Comment by FR4385** [comment]
I checked again and I am getting some returns.   Earlier I reached out to coworkers, and they had no returns either.

**Comment by FR4385** [comment]
Thanks
