### ISSUE TITLE
Typo Fix: Part 5: Turn Search into Workflow

### ISSUE THREAD

**Issue by ronsanchez-ms** [rod-trent/MustLearnKQL#28]
> So, now that we’ve found something interesting, we want to use the structure of the Search Query to pare down the results to minimize the effort and workload to identify that that something interesting is actually something notable and worth investigating.

Should be...(omit extra "that")

So, now that we’ve found something interesting, we want to use the structure of the Search Query to pare down the results to minimize the effort and workload to identify that ~~**that**~~ something interesting is actually something notable and worth investigating.

**Comment by rod-trent** [comment]
Resolved
