### ISSUE TITLE
Reference to Part 1 DNS-errors

### ISSUE THREAD

**Issue by Manbearpiet** [rod-trent/MustLearnKQL#7]
None of the links deliver the page it's linked to. https://raw.githubusercontent.com/rod-trent/MustLearnKQL/main/Book_Version/MustLearnKQL_Book.pdf. I also tried downloading the book, this doesn't make a difference either.
These all deliver similar DNS errors for me:
https://cda.ms/3fH
https://cda.ms/3fm
![image](https://user-images.githubusercontent.com/43993129/176675606-66b6b963-f2e7-4bc1-b6a1-8df6c4caf63d.png)

**Comment by rod-trent** [comment]
Resolved with new links.
